const countries = [
    { value: "AF", name: "Afghanistan", code: "+93" },
    { value: "AL", name: "Albania", code: "+355" },
    { value: "DZ", name: "Algeria", code: "+213" },
    { value: "AS", name: "American Samoa", code: "+1" },
    { value: "AD", name: "Andorra", code: "+376" },
    { value: "AO", name: "Angola", code: "+244" },
    { value: "AI", name: "Anguilla", code: "+1" },
    { value: "AG", name: "Antigua", code: "+1" },
    { value: "AR", name: "Argentina", code: "+54" },
    { value: "AM", name: "Armenia", code: "+374" },
    { value: "AW", name: "Aruba", code: "+297" },
    { value: "AU", name: "Australia", code: "+61" },
    { value: "AT", name: "Austria", code: "+43" },
    { value: "AZ", name: "Azerbaijan", code: "+994" },
    { value: "BH", name: "Bahrain", code: "+973" },
    { value: "BD", name: "Bangladesh", code: "+880" },
    { value: "BB", name: "Barbados", code: "+1" },
    { value: "BY", name: "Belarus", code: "+375" },
    { value: "BE", name: "Belgium", code: "+32" },
    { value: "BZ", name: "Belize", code: "+501" },
    { value: "BJ", name: "Benin", code: "+229" },
    { value: "BM", name: "Bermuda", code: "+1" },
    { value: "BT", name: "Bhutan", code: "+975" },
    { value: "BO", name: "Bolivia", code: "+591" },
    { value: "BA", name: "Bosnia and Herzegovina", code: "+387" },
    { value: "BW", name: "Botswana", code: "+267" },
    { value: "BR", name: "Brazil", code: "+55" },
    { value: "IO", name: "British Indian Ocean Territory", code: "+246" },
    { value: "VG", name: "British Virgin Islands", code: "+1" },
    { value: "BN", name: "Brunei", code: "+673" },
    { value: "BG", name: "Bulgaria", code: "+359" },
    { value: "BF", name: "Burkina Faso", code: "+226" },
    { value: "MM", name: "Burma Myanmar", code: "+95" },
    { value: "BI", name: "Burundi", code: "+257" },
    { value: "KH", name: "Cambodia", code: "+855" },
    { value: "CM", name: "Cameroon", code: "+237" },
    { value: "CA", name: "Canada", code: "+1" },
    { value: "CV", name: "Cape Verde", code: "+238" },
    { value: "KY", name: "Cayman Islands", code: "+1" },
    { value: "CF", name: "Central African Republic", code: "+236" },
    { value: "TD", name: "Chad", code: "+235" },
    { value: "CL", name: "Chile", code: "+56" },
    { value: "CN", name: "China", code: "+86" },
    { value: "CO", name: "Colombia", code: "+57" },
    { value: "KM", name: "Comoros", code: "+269" },
    { value: "CK", name: "Cook Islands", code: "+682" },
    { value: "CR", name: "Costa Rica", code: "+506" },
    { value: "CI", name: "Côte d'Ivoire", code: "+225" },
    { value: "HR", name: "Croatia", code: "+385" },
    { value: "CU", name: "Cuba", code: "+53" },
    { value: "CY", name: "Cyprus", code: "+357" },
    { value: "CZ", name: "Czech Republic", code: "+420" },
    { value: "CD", name: "Democratic Republic of Congo", code: "+243" },
    { value: "DK", name: "Denmark", code: "+45" },
    { value: "DJ", name: "Djibouti", code: "+253" },
    { value: "DM", name: "Dominica", code: "+1" },
    { value: "DO", name: "Dominican Republic", code: "+1" },
    { value: "EC", name: "Ecuador", code: "+593" },
    { value: "EG", name: "Egypt", code: "+20" },
    { value: "SV", name: "El Salvador", code: "+503" },
    { value: "GQ", name: "Equatorial Guinea", code: "+240" },
    { value: "ER", name: "Eritrea", code: "+291" },
    { value: "EE", name: "Estonia", code: "+372" },
    { value: "ET", name: "Ethiopia", code: "+251" },
    { value: "FK", name: "Falkland Islands", code: "+500" },
    { value: "FO", name: "Faroe Islands", code: "+298" },
    { value: "FM", name: "Federated States of Micronesia", code: "+691" },
    { value: "FJ", name: "Fiji", code: "+679" },
    { value: "FI", name: "Finland", code: "+358" },
    { value: "FR", name: "France", code: "+33" },
    { value: "GF", name: "French Guiana", code: "+594" },
    { value: "PF", name: "French Polynesia", code: "+689" },
    { value: "GA", name: "Gabon", code: "+241" },
    { value: "GE", name: "Georgia", code: "+995" },
    { value: "DE", name: "Germany", code: "+49" },
    { value: "GH", name: "Ghana", code: "+233" },
    { value: "GI", name: "Gibraltar", code: "+350" },
    { value: "GR", name: "Greece", code: "+30" },
    { value: "GL", name: "Greenland", code: "+299" },
    { value: "GD", name: "Grenada", code: "+1" },
    { value: "GP", name: "Guadeloupe", code: "+590" },
    { value: "GU", name: "Guam", code: "+1" },
    { value: "GT", name: "Guatemala", code: "+502" },
    { value: "GN", name: "Guinea", code: "+224" },
    { value: "GW", name: "Guinea-Bissau", code: "+245" },
    { value: "GY", name: "Guyana", code: "+592" },
    { value: "HT", name: "Haiti", code: "+509" },
    { value: "HN", name: "Honduras", code: "+504" },
    { value: "HK", name: "Hong Kong", code: "+852" },
    { value: "HU", name: "Hungary", code: "+36" },
    { value: "IS", name: "Iceland", code: "+354" },
    { value: "IN", name: "India", code: "+91" },
    { value: "ID", name: "Indonesia", code: "+62" },
    { value: "IR", name: "Iran", code: "+98" },
    { value: "IQ", name: "Iraq", code: "+964" },
    { value: "IE", name: "Ireland", code: "+353" },
    { value: "IL", name: "Israel", code: "+972" },
    { value: "IT", name: "Italy", code: "+39" },
    { value: "JM", name: "Jamaica", code: "+1" },
    { value: "JP", name: "Japan", code: "+81" },
    { value: "JO", name: "Jordan", code: "+962" },
    { value: "KZ", name: "Kazakhstan", code: "+7" },
    { value: "KE", name: "Kenya", code: "+254" },
    { value: "KI", name: "Kiribati", code: "+686" },
    { value: "SO", name: "Somalia", code: "+252" },
    { value: "ZA", name: "South Africa", code: "+27" },
    { value: "KR", name: "South Korea", code: "+82" },
    { value: "ES", name: "Spain", code: "+34" },
    { value: "LK", name: "Sri Lanka", code: "+94" },
    { value: "LC", name: "St. Lucia", code: "+1" },
    { value: "SD", name: "Sudan", code: "+249" },
    { value: "SR", name: "Suriname", code: "+597" },
    { value: "SZ", name: "Swaziland", code: "+268" },
    { value: "SE", name: "Sweden", code: "+46" },
    { value: "CH", name: "Switzerland", code: "+41" },
    { value: "SY", name: "Syria", code: "+963" },
    { value: "TW", name: "Taiwan", code: "+886" },
    { value: "TJ", name: "Tajikistan", code: "+992" },
    { value: "TZ", name: "Tanzania", code: "+255" },
    { value: "TH", name: "Thailand", code: "+66" },
    { value: "BS", name: "The Bahamas", code: "+1" },
    { value: "GM", name: "The Gambia", code: "+220" },
    { value: "TL", name: "Timor-Leste", code: "+670" },
    { value: "TG", name: "Togo", code: "+228" },
    { value: "TK", name: "Tokelau", code: "+690" },
    { value: "TO", name: "Tonga", code: "+676" },
    { value: "TT", name: "Trinidad and Tobago", code: "+1" },
    { value: "TN", name: "Tunisia", code: "+216" },
    { value: "TR", name: "Turkey", code: "+90" },
    { value: "TM", name: "Turkmenistan", code: "+993" },
    { value: "TC", name: "Turks and Caicos Islands", code: "+1" },
    { value: "TV", name: "Tuvalu", code: "+688" },
    { value: "UG", name: "Uganda", code: "+256" },
    { value: "UA", name: "Ukraine", code: "+380" },
    { value: "AE", name: "United Arab Emirates", code: "+971" },
    { value: "GB", name: "United Kingdom", code: "+44" },
    { value: "US", name: "United States", code: "+1" },
    { value: "UY", name: "Uruguay", code: "+598" },
    { value: "VI", name: "US Virgin Islands", code: "+1" },
    { value: "UZ", name: "Uzbekistan", code: "+998" },
    { value: "VU", name: "Vanuatu", code: "+678" },
    { value: "VA", name: "Vatican City", code: "+39" },
    { value: "VE", name: "Venezuela", code: "+58" },
    { value: "VN", name: "Vietnam", code: "+84" },
    { value: "WF", name: "Wallis and Futuna", code: "+681" },
    { value: "YE", name: "Yemen", code: "+967" },
    { value: "ZM", name: "Zambia", code: "+260" },
    { value: "ZW", name: "Zimbabwe", code: "+263" }
];

export default countries;
